### ISSUE TITLE
`|is<T>` accepts anything on the left side

### ISSUE THREAD

**Issue by tamaskenez** [AVasK/vx#1]
Because of this constructor:

```c++
template< class ValueType >
std::any( ValueType&& value );
```

the expression `x |is<T>` compiles even if `x` is not one of `std::optional`, `std::variant`, `std::any`. As opposed to `std::holds_alternative<T>(x)` which is an error if `x` is not a `std::variant`.

I'm not sure if this is by design but it's also error prone since, for example, we mean `x.variantField |is<T>` but by mistake we write `x |is<T>` and it's a good thing if the compiler catches it.

Proposed fix:
```c++
template<typename Any, typename Type>
requires std::is_same_v<Any, std::any>
constexpr bool operator|(Any const& a, compare<Type>) { ...
```

**Comment by AVasK** [comment]
Thanks for this finding! Yes, I agree, this behaviour is error-prone and should be fixed.

**Comment by AVasK** [comment]
A belated fix done)
