### ISSUE TITLE
Fails with lambda with reference parameter

### ISSUE THREAD

**Issue by rodrigocfd** [AVasK/vx#2]
Given:

```cpp
std::variant<int, std::string> varx;
```

This works:

```cpp
varx | match {
	[](int n) { },
	[](std::string s) { }, // <--- by value
};
```

But this **fails**:

```cpp
varx | match {
	[](int n) { },
	[](std::string& s) { }, // <--- by reference
};
```

Note that calling `std::visit` **does work** with the parameter passed by reference:

```cpp
std::visit(match {
	[](int n) { },
	[](std::string& s) { },
}, varx);
```

**Comment by AVasK** [comment]
Hi Rodrigo, thanks, actually forgot to update the repo version, that's an easy fix - the overload for operator| taking the non-const reference was just missing :) Thanks for spotting that! Please check out the latest commit, I believe that it should be fixed now.

**Comment by rodrigocfd** [comment]
Looks good to me, thanks dude.
